# Generated by Django 6.0.1 on 2026-01-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_add_justification_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_fcaba7_idx',
            old_name='expenses_exp_category_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_status_cbb790_idx',
            old_name='expenses_exp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_date_17a2b2_idx',
            old_name='expenses_exp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_deleted_75e294_idx',
            old_name='expenses_exp_deleted__idx',
        ),
    ]
