# Generated by Django 6.0.1 on 2026-01-26 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name="Numéro d'intervention")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du client')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone client')),
                ('client_address', models.TextField(blank=True, null=True, verbose_name="Adresse d'intervention")),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Priorité')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes techniques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.client', verbose_name='Client')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité utilisée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='interventions.intervention', verbose_name='Intervention')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Produit d'intervention",
                'verbose_name_plural': "Produits d'intervention",
                'unique_together': {('intervention', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status'], name='intervention_status_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['technician'], name='intervention_technician_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['scheduled_date'], name='intervention_scheduled_date_idx'),
        ),
    ]
