# Generated by Django 6.0.1 on 2026-01-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intervention',
            new_name='interventio_status_b4f56c_idx',
            old_name='intervention_status_idx',
        ),
        migrations.RenameIndex(
            model_name='intervention',
            new_name='interventio_technic_df8a79_idx',
            old_name='intervention_technician_idx',
        ),
        migrations.RenameIndex(
            model_name='intervention',
            new_name='interventio_schedul_29e7ee_idx',
            old_name='intervention_scheduled_date_idx',
        ),
    ]
