# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_rename_intervention_status_idx_interventio_status_b4f56c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
