# Generated by Django 6.0.1 on 2026-01-26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name="Numéro d'installation")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('installation_type', models.CharField(choices=[('EQUIPEMENT', 'Équipement'), ('SYSTEME', 'Système'), ('RESEAU', 'Réseau'), ('LOGICIEL', 'Logiciel'), ('AUTRE', 'Autre')], default='EQUIPEMENT', max_length=20, verbose_name="Type d'installation")),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du client')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone client')),
                ('client_address', models.TextField(blank=True, null=True, verbose_name="Adresse d'installation")),
                ('status', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('warranty_period', models.IntegerField(blank=True, null=True, verbose_name='Période de garantie (mois)')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de garantie')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes techniques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.client', verbose_name='Client')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité utilisée')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de série')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='installations.installation', verbose_name='Installation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Produit d'installation",
                'verbose_name_plural': "Produits d'installation",
                'unique_together': {('installation', 'product', 'serial_number')},
            },
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['status'], name='installatio_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['technician'], name='installatio_technic_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['scheduled_date'], name='installatio_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['installation_type'], name='installatio_type_idx'),
        ),
    ]
