# Generated by Django 6.0.1 on 2026-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='installation',
            new_name='installatio_status_0e0ae0_idx',
            old_name='installatio_status_idx',
        ),
        migrations.RenameIndex(
            model_name='installation',
            new_name='installatio_technic_5c414c_idx',
            old_name='installatio_technic_idx',
        ),
        migrations.RenameIndex(
            model_name='installation',
            new_name='installatio_schedul_a104dc_idx',
            old_name='installatio_schedule_idx',
        ),
        migrations.RenameIndex(
            model_name='installation',
            new_name='installatio_install_6ee7ba_idx',
            old_name='installatio_type_idx',
        ),
    ]
