# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_rename_installatio_status_idx_installatio_status_0e0ae0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
