# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('radius_m', models.DecimalField(decimal_places=2, help_text='Rayon de la zone en mètres', max_digits=10, verbose_name='Rayon (m)')),
                ('zone_type', models.CharField(choices=[('bureau', 'Bureau'), ('chantier', 'Chantier')], default='bureau', max_length=20, verbose_name='Type de zone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Zone de travail',
                'verbose_name_plural': 'Zones de travail',
                'ordering': ['-created_at'],
            },
        ),
    ]
