# Generated by Django 6.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
