# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='work_zone',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pointages',
                to='zones.workzone',
                verbose_name='Zone de travail',
            ),
        ),
    ]
