# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_checkin_work_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude au pointage'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude au pointage'),
        ),
    ]
